"""
render.py — Advanced: custom clip order

Use this when you want manual control over which clips appear and in what order.
For automatic rendering, use run.py instead.

Workflow:
  1. Run run.py (or cs2montage scan+detect_kills+save) to generate output/clips.json
  2. Look at output/clips.json to find clip indices
  3. Edit TIMELINE below with the indices you want
  4. Run: python render.py
"""

import os, sys, json, traceback
sys.stdout.reconfigure(encoding="utf-8", errors="replace")

from moviepy import VideoFileClip, concatenate_videoclips

_HERE      = os.path.dirname(os.path.abspath(__file__))
SOURCE_DIR = os.path.join(_HERE, "source")
OUTPUT_DIR = os.path.join(_HERE, "output")
CLIPS_JSON = os.path.join(OUTPUT_DIR, "clips.json")   # generated by cs2montage.save()

os.makedirs(OUTPUT_DIR, exist_ok=True)

# ── Timing ────────────────────────────────────────────────────────────────────
PRE_SEC  = 2.0   # seconds before first kill
POST_SEC = 0.5   # seconds after last kill
MAX_CLIP = 7.0   # max clip length (seconds); set to None to disable
FPS      = 60

# ── Timeline ──────────────────────────────────────────────────────────────────
# Each entry: (index_in_clips_json, label, pre_override, post_override)
#   index       : position of the clip in output/clips.json (0-based)
#   label       : shown in progress output
#   pre_override : seconds before first kill (None = use PRE_SEC)
#   post_override: seconds after last kill   (None = use POST_SEC)
#
# Run:  python -c "import json; [print(i, c['type'], c['file'][:60]) for i,c in enumerate(json.load(open('output/clips.json')))]"
# to list clip indices.

TIMELINE = [
    # (index, label,     pre_override, post_override)
    (0,   "clip_01",  None,  None),
    (1,   "clip_02",  None,  None),
    (2,   "clip_03",  None,  None),
    # add more clips...
    # last clip example with extended ending:
    # (5, "finale",  5.0,  3.0),
]


# ── Core ──────────────────────────────────────────────────────────────────────

def process_clip(clip: dict, label: str,
                 pre_override=None, post_override=None) -> "VideoClip":
    src  = clip.get("path") or os.path.join(SOURCE_DIR, clip["file"])
    dur  = clip["duration_total"]
    pre  = pre_override  if pre_override  is not None else PRE_SEC
    post = post_override if post_override is not None else POST_SEC
    tail = 3.5

    first_k = clip.get("kill_first", dur - tail)
    last_k  = clip.get("kill_last",  first_k)

    ts = max(0.0, first_k - pre)
    te = min(dur, last_k + post)

    if MAX_CLIP and pre_override is None and post_override is None:
        if (te - ts) > MAX_CLIP:
            te = ts + MAX_CLIP

    print(f"  [{label}] {clip['type']:<12} kills: {first_k:.1f}s–{last_k:.1f}s  "
          f"window: {ts:.1f}s–{te:.1f}s")

    return VideoFileClip(src).subclipped(ts, te).without_audio()


def main():
    with open(CLIPS_JSON, encoding="utf-8") as f:
        clips = json.load(f)

    print(f"Loaded {len(clips)} clips from clips.json")
    print(f"Rendering {len(TIMELINE)} clips from TIMELINE\n")

    rendered = []
    for (idx, label, pre_ov, post_ov) in TIMELINE:
        clip = clips[idx]
        print(f"[{label}] {clip['file'][:65]}")
        try:
            rendered.append(process_clip(clip, label, pre_ov, post_ov))
        except Exception as e:
            print(f"  ERROR: {e}")
            traceback.print_exc()
        print()

    if not rendered:
        print("No clips rendered.")
        return

    print(f"Concatenating {len(rendered)} clips...")
    final = concatenate_videoclips(rendered, method="compose")
    print(f"Duration: {final.duration:.1f}s ({final.duration/60:.1f} min)")

    out = os.path.join(OUTPUT_DIR, "final_highlight.mp4")
    final.write_videofile(out, fps=FPS, codec="libx264",
                          ffmpeg_params=["-preset", "fast", "-crf", "18"],
                          logger="bar")
    for v in rendered:
        v.close()
    final.close()
    print(f"\nDone: {out}")


if __name__ == "__main__":
    main()
